#merp
botToken: OTE0MzM3MDU2MDA2NzU4NDEw.YaLkvQ.yn_lhqYPVWYGIMbc2GeFN3xJqJA
discordServerID: 832884556373032972
discordChatChannelID: 898376463395471401
discordStaffChannelID: 916468989675323433
subroleID: 840361518792179752
adverts:
  - "%blue%Click here to join our &lDISCORD&r%blue%!%discord%"
  - "%purple%Remember to follow Midnight City on twitch!%twitch%"
  - "%green%Remember, Ender Eyes are crafted with a nether star!"
  - "%blue%Click here to join our discord!%discord%"
  - "%purple%Remember to follow Midnight City on twitch!%twitch%"
  - "%orange%If you die your items will be voided."
  - "%blue%Click here to join our discord!%discord%"
  - "%purple%Remember to follow Midnight City on &lTWITCH&r%purple%!%twitch%"